const data = {
    telaviv:{
        name: "Tel Aviv",
        cover: "url('https://images.unsplash.com/photo-1544519685-0e27154e8352?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1489&q=80')",
        meta_title: "Best Virtual Assistants in Tel Aviv, Virtual Assistant Services in Tel Aviv",
        meta_description: "Get the best virtual assistant services in Tel Aviv. Wishup provides virtual or remote assistants in Dallas from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Tel Aviv Virtual Assistant Services | Hire Remote Assistants in Tel Aviv",
        og_description: "Save time with our Virtual Assistant Services in Tel Aviv! Wishup pioneers in providing virtual assistant or remote assistant services in Tel Aviv.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    newyork:{
        name: "New York",
        cover: "url('https://images.unsplash.com/photo-1523128662036-c964212cc9f0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1226&q=80')",
        meta_title: "Best Virtual Assistants in New York, Virtual Assistant Services in New York",
        meta_description: "Get the best virtual assistant services in New York. Wishup provides virtual or remote assistants in Dallas from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "New York Virtual Assistant Services | Hire Remote Assistants in New York",
        og_description: "Save time with our Virtual Assistant Services in New York! Wishup pioneers in providing virtual assistant or remote assistant services in Tel Aviv.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    losangeles:{
        name: "Los Angeles",
        cover: "url('https://images.unsplash.com/photo-1515896769750-31548aa180ed?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1434&q=80')",
        meta_title: "Best Virtual Assistants in Los Angeles, Virtual Assistant Services in Los Angeles",
        meta_description: "Get the best virtual assistant services in Los Angeles. Wishup provides virtual or remote assistants in Los Angeles from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Los Angeles Virtual Assistant Services | Hire Remote Assistants in Los Angeles",
        og_description: "Save time with our Virtual Assistant Services in Los Angeles! Wishup pioneers in providing virtual assistant or remote assistant services in Los Angeles.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    dallas:{
        name: "Dallas",
        cover: "url('https://images.unsplash.com/photo-1515623844043-1ceda251d277?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in Dallas, Virtual Assistant Services in Dallas",
        meta_description: "Get the best virtual assistant services in Dallas. Wishup provides virtual or remote assistants in Dallas from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Dallas Virtual Assistant Services | Hire Remote Assistants in Dallas",
        og_description: "Save time with our Virtual Assistant Services in Dallas! Wishup pioneers in providing virtual assistant or remote assistant services in Dallas.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    chicago:{
        name: "Chicago",
        cover: "url('https://images.unsplash.com/photo-1524168272322-bf73616d9cb5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in Chicago, Virtual Assistant Services in Chicago",
        meta_description: "Get the best virtual assistant services in Chicago. Wishup provides virtual or remote assistants in Chicago from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Chicago Virtual Assistant Services | Hire Remote Assistants in Chicago",
        og_description: "Save time with our Virtual Assistant Services in Chicago! Wishup pioneers in providing virtual assistant or remote assistant services in Chicago.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    houston:{
        name: "Houston",
        cover: "url('https://images.unsplash.com/photo-1470082719408-b2843ab5c9ab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1491&q=80')",
        meta_title: "Best Virtual Assistants in Houston, Virtual Assistant Services in Houston",
        meta_description: "Get the best virtual assistant services in Houston. Wishup provides virtual or remote assistants in Houston from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Houston Virtual Assistant Services | Hire Remote Assistants in Houston",
        og_description: "Save time with our Virtual Assistant Services in Houston! Wishup pioneers in providing virtual assistant or remote assistant services in Houston.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    sanfrancisco:{
        name: "San Francisco",
        cover: "url('https://images.unsplash.com/photo-1534513428988-e6ae8e14a629?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in San Francisco, Virtual Assistant Services in San Francisco",
        meta_description: "Get the best virtual assistant services in San Francisco. Wishup provides virtual or remote assistants in San Francisco from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "San Francisco Virtual Assistant Services | Hire Remote Assistants in San Francisco",
        og_description: "Save time with our Virtual Assistant Services in San Francisco! Wishup pioneers in providing virtual assistant or remote assistant services in San Francisco.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    austin:{
        name: "Austin",
        cover: "url('https://images.unsplash.com/photo-1531218150217-54595bc2b934?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1400&q=80')",
        meta_title: "Best Virtual Assistants in Austin, Virtual Assistant Services in Austin",
        meta_description: "Get the best virtual assistant services in Austin. Wishup provides virtual or remote assistants in Austin from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Austin Virtual Assistant Services | Hire Remote Assistants in Austin",
        og_description: "Save time with our Virtual Assistant Services in Austin! Wishup pioneers in providing virtual assistant or remote assistant services in Austin.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    toronto:{
        name: "Chicago",
        cover: "url('https://images.unsplash.com/photo-1486325212027-8081e485255e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in Chicago, Virtual Assistant Services in Chicago",
        meta_description: "Get the best virtual assistant services in Chicago. Wishup provides virtual or remote assistants in Chicago from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Chicago Virtual Assistant Services | Hire Remote Assistants in Chicago",
        og_description: "Save time with our Virtual Assistant Services in Chicago! Wishup pioneers in providing virtual assistant or remote assistant services in Chicago.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    vancouver:{
        name: "Vancouver",
        cover: "url('https://images.unsplash.com/photo-1519181258491-889c2b001485?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in Vancouver, Virtual Assistant Services in Vancouver",
        meta_description: "Get the best virtual assistant services in Vancouver. Wishup provides virtual or remote assistants in Vancouver from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Vancouver Virtual Assistant Services | Hire Remote Assistants in Vancouver",
        og_description: "Save time with our Virtual Assistant Services in Vancouver! Wishup pioneers in providing virtual assistant or remote assistant services in Vancouver.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    seattle:{
        name: "Seattle",
        cover: "url('https://images.unsplash.com/photo-1469321461812-afeb94496b27?ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80')",
        meta_title: "Best Virtual Assistants in Seattle, Virtual Assistant Services in Seattle",
        meta_description: "Get the best virtual assistant services in Seattle. Wishup provides virtual or remote assistants in Seattle from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Seattle Virtual Assistant Services | Hire Remote Assistants in Seattle",
        og_description: "Save time with our Virtual Assistant Services in Seattle! Wishup pioneers in providing virtual assistant or remote assistant services in Seattle.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    uk:{
        name: "UK",
        cover: "url('https://images.unsplash.com/photo-1508711046474-2f4c2d3d30ca?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in UK, Virtual Assistant Services in UK",
        meta_description: "Get the best virtual assistant services in UK. Wishup provides virtual or remote assistants in UK from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "UK Virtual Assistant Services | Hire Remote Assistants in UK",
        og_description: "Save time with our Virtual Assistant Services in UK! Wishup pioneers in providing virtual assistant or remote assistant services in UK.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    london:{
        name: "London",
        cover: "url('https://images.unsplash.com/photo-1508711046474-2f4c2d3d30ca?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in London, Virtual Assistant Services in London",
        meta_description: "Get the best virtual assistant services in London. Wishup provides virtual or remote assistants in London from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "London Virtual Assistant Services | Hire Remote Assistants in London",
        og_description: "Save time with our Virtual Assistant Services in London! Wishup pioneers in providing virtual assistant or remote assistant services in London.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    berlin:{
        name: "Berlin",
        cover: "url('https://images.unsplash.com/photo-1534595277048-5eefc67087f5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1351&q=80')",
        meta_title: "Best Virtual Assistants in Berlin, Virtual Assistant Services in Berlin",
        meta_description: "Get the best virtual assistant services in Berlin. Wishup provides virtual or remote assistants in Berlin from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Berlin Virtual Assistant Services | Hire Remote Assistants in Berlin",
        og_description: "Save time with our Virtual Assistant Services in Berlin! Wishup pioneers in providing virtual assistant or remote assistant services in Berlin.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    paris:{
        name: "Paris",
        cover: "url('https://images.unsplash.com/photo-1502602898657-3e91760cbb34?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80')",
        meta_title: "Best Virtual Assistants in Paris, Virtual Assistant Services in Paris",
        meta_description: "Get the best virtual assistant services in Paris. Wishup provides virtual or remote assistants in Paris from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Paris Virtual Assistant Services | Hire Remote Assistants in Paris",
        og_description: "Save time with our Virtual Assistant Services in Paris! Wishup pioneers in providing virtual assistant or remote assistant services in Paris.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    dublin:{
        name: "Dublin",
        cover: "url('https://images.unsplash.com/photo-1488155436641-58ef42fcc44e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80')",
        meta_title: "Best Virtual Assistants in Dublin, Virtual Assistant Services in Dublin",
        meta_description: "Get the best virtual assistant services in Dublin. Wishup provides virtual or remote assistants in Dublin from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Dublin Virtual Assistant Services | Hire Remote Assistants in Dublin",
        og_description: "Save time with our Virtual Assistant Services in Dublin! Wishup pioneers in providing virtual assistant or remote assistant services in Dublin.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    dubai:{
        name: "Dubai",
        cover: "url('https://images.unsplash.com/photo-1522384731535-d1ccd4345321?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1544&q=80')",
        meta_title: "Best Virtual Assistants in Dubai, Virtual Assistant Services in Dubai",
        meta_description: "Get the best virtual assistant services in Dubai. Wishup provides virtual or remote assistants in Dubai from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Dubai Virtual Assistant Services | Hire Remote Assistants in Dubai",
        og_description: "Save time with our Virtual Assistant Services in Dubai! Wishup pioneers in providing virtual assistant or remote assistant services in Dubai.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    abudhabhi:{
        name: "Abu Dhabhi",
        cover: "url('https://images.unsplash.com/photo-1510773011259-71baf5d72aea?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1264&q=80')",
        meta_title: "Best Virtual Assistants in Abu Dhabhi, Virtual Assistant Services in Abu Dhabhi",
        meta_description: "Get the best virtual assistant services in Abu Dhabhi. Wishup provides virtual or remote assistants in Abu Dhabhi from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Abu Dhabhi Virtual Assistant Services | Hire Remote Assistants in Abu Dhabhi",
        og_description: "Save time with our Virtual Assistant Services in Abu Dhabhi! Wishup pioneers in providing virtual assistant or remote assistant services in Abu Dhabhi.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    singapore:{
        name: "Singapore",
        cover: "url('https://images.unsplash.com/photo-1493540554008-8e3008329feb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in Singapore, Virtual Assistant Services in Singapore",
        meta_description: "Get the best virtual assistant services in Singapore. Wishup provides virtual or remote assistants in Singapore from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Singapore Virtual Assistant Services | Hire Remote Assistants in Singapore",
        og_description: "Save time with our Virtual Assistant Services in Singapore! Wishup pioneers in providing virtual assistant or remote assistant services in Singapore.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    sydney:{
        name: "Sydney",
        cover: "url('https://images.unsplash.com/photo-1532984601283-d68a3ee3e51f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1964&q=80')",
        meta_title: "Best Virtual Assistants in Sydney, Virtual Assistant Services in Sydney",
        meta_description: "Get the best virtual assistant services in Sydney. Wishup provides virtual or remote assistants in Sydney from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Sydney Virtual Assistant Services | Hire Remote Assistants in Sydney",
        og_description: "Save time with our Virtual Assistant Services in Sydney! Wishup pioneers in providing virtual assistant or remote assistant services in Sydney.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    hongkong:{
        name: "Hong Kong",
        cover: "url('https://images.unsplash.com/photo-1517144447511-aebb25bbc5fa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in Hong Kong, Virtual Assistant Services in Hong Kong",
        meta_description: "Get the best virtual assistant services in Hong Kong. Wishup provides virtual or remote assistants in Hong Kong from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Hong Kong Virtual Assistant Services | Hire Remote Assistants in Hong Kong",
        og_description: "Save time with our Virtual Assistant Services in Hong Kong! Wishup pioneers in providing virtual assistant or remote assistant services in Hong Kong.  +Professional Assistants +Customer Support Available",
        description: "",
    },
    shanghai:{
        name: "Shanghai",
        cover: "url('https://images.unsplash.com/photo-1538428494232-9c0d8a3ab403?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')",
        meta_title: "Best Virtual Assistants in Shanghai, Virtual Assistant Services in Shanghai",
        meta_description: "Get the best virtual assistant services in Shanghai. Wishup provides virtual or remote assistants in Shanghai from every domain be it medical, real estate, marketing, finance or anything. +Highly Qualified Professionals +Customer Support Available",
        og_title: "Shanghai Virtual Assistant Services | Hire Remote Assistants in Shanghai",
        og_description: "Save time with our Virtual Assistant Services in Shanghai! Wishup pioneers in providing virtual assistant or remote assistant services in Shanghai.  +Professional Assistants +Customer Support Available",
        description: "",
    }
};

export default data;
